# Basic Python

## 1. Split this string

In [10]:
s = "Hi there Sam!"

In [11]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742

In [9]:
print("The diameter of {} is {} kilometers".format(planet, diameter) )


The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


In [22]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [25]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [29]:
a0=np.zeros(10,int) 
a0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
a5=np.array([5,5,5,5,5,5,5,5,5,5])
a5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [42]:
for i in range (20,35):
    if i%2==0:
        print(i)

20
22
24
26
28
30
32
34


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:

mat3= np.array([[0,1,2],[3,4,5],[6,7,8]])
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
[*a,*b]

[1, 2, 3, 4, 5, 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [61]:
import pandas as pd

In [63]:
dictn={'Name':['john','david','maria'],'Age':[10,23,24]}

In [69]:

data=pd.DataFrame({'Name':['john','david','maria'],'Age':[10,23,24]})
data

Name  Age
0   john   10
1  david   23
2  maria   24

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [88]:
import datetime
start = datetime.date(2023,1,1)
k= 41
res = []

for day in range(k):
	date = (start + datetime.timedelta(days = day)).isoformat()
	res.append(date)

print("Next K dates list: " + str(res))


Next K dates list: ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12', '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20', '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24', '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28', '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09', '2023-02-10']


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [79]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [81]:
dt=pd.DataFrame(lists)
dt

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24